name: Windows Build and Release

on:
  workflow_dispatch: # 手动触发

permissions:
  contents: write # 确保拥有写入权限

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      # 清理和构建 Windows Release 版本
      - name: Build Windows Release
        run: |
          flutter clean
          flutter build windows --release

      # 创建输出目录并复制文件
      - name: Prepare Release Files
        run: |
          mkdir output/windows -Force
          Copy-Item build/windows/x64/runner/Release/*.exe output/windows/
          Copy-Item build/windows/x64/runner/Release/*.dll output/windows/
          if (Test-Path build/windows/x64/runner/Release/icudtl.dat) {
            Copy-Item build/windows/x64/runner/Release/icudtl.dat output/windows/
          } else {
            Write-Host "icudtl.dat not found, skipping."
          }

      # 打包成 ZIP 文件
      - name: Create ZIP Package
        run: |
          Compress-Archive -Path output/windows/* -DestinationPath output/windows-release.zip

      # 上传 ZIP 文件到 GitHub Actions 的工件
      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-zip
          path: output/windows-release.zip

      # 自动发布 Release 并上传 ZIP 文件
      - name: Create GitHub Release with ZIP
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/windows-release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Windows Release - ${{ github.ref_name }}"
          body: |
            This release includes the following updates:
            - Windows build packaged as a ZIP file.
          draft: false
          prerelease: false
